@startuml
'https://plantuml.com/class-diagram

class Instructor{
- firstName : String [1]
- lastName : String [1]
- officeNumber : String [1]

+ getFirstName() : String
+ setFirstName(in firstName : String) : void
+ getLastName() : String
+ setLastName(in lastName : String) : void
+ getOfficeNumber() : String
+ setOfficeNumber(in officeNumber : String) : void
+ toString() : String
}

class Textbook{
    - title : String [1]
    - author : String [1]
    - publisher : String [1]

    + getTitle() : String
    + setTitle(in title : String) : void
    + getAuthor() : String
    + setAuthor(in author: String): void
    + getPublisher() : String
    + setPublisher(in publisher: String) : void
    + toString() : String
}

class Course{
- name : String [1]
- instructors : Instructor [*]
- textbooks : Textbook [*]

+ Course() : Course
+ getName() : String
+ setName(int name: String):void
+ getInstructors() : Instructor [*]
+ setInstructor(in instructor : Instructor): void
+ getTextbooks() : Textbook [*]
+ setTextbook(in textbook : Textbook) : void
+ toString() : String
+ printCourse() : void

}

Course o-- Instructor
Course o-- Textbook


@enduml