@startuml
'https://plantuml.com/class-diagram


abstract class Employee{
- firstName : String [1]
- lastName : String [1]
- socialSecurityNumber : String [1]

+ getFirstName() : String [1]
+ setFirstName(in firstName : String) : void
+ getLastName() : String
+ setLastName(in lastName : String) : void
+ getSocialSecurityNumber() : String
+ setSocialSecurityNumber(in socialSecurityNumber : String) : void
+ toString() : String
}

class SalariedEmployee{
   - weeklySalary : int [1]
   + getWeeklySalary() : int
   + setWeeklySalary(in weeklySalary : int) : void
   + toString() : String
}

class HourlyEmployee{
- wage : int [1]
- hoursWorked: int [1]

+ getWage() : int
+ setWage(in wage : int) : void
+ getHoursWorked() : int
+ setHoursWorked(in hoursWorked) : void
+ toString() : String
}

class CommisionEmployee{
- commissionRate : int [1]
- grossSales : int[1]

+ getCommissionRate() : int
+ setCommissionRate(in commissionRate:int) : void
+ getGrossSales() : int
+ setGrossSales(in grossSales : int) : void
+ toString() : String
}

class BaseEmployee{
- baseSalary : int [1]

+ getBaseSalary() : int
+ setBaseSalary(in baseSalary : int) : void

+ toString() : String
}


Employee <|-- SalariedEmployee
Employee <|-- HourlyEmployee
Employee <|-- CommisionEmployee
Employee <|-- BaseEmployee

@enduml

