@startuml
'https://plantuml.com/class-diagram

class Ship{
# shipName : String [1]
# yearBuilt : String [1]

+ getShipName() : String
+ setShipName(in shipName : String) : void
+ getYearBuilt() : String
+ setYearBuilt(in yearBuilt : String) : void
+ toString() : String
+ printShip() : void
}

class CargoShip{
- cargoCapacityInTonnage: int [1]

+ getCargoCapacityInTonnage() : int
+ setCargoCapacityInTonnage(in cargoCapacityInTonnage : int) : void
+ toString() : String

}

class CruiseShip{
- maxNumberPassengers : int [1]

+ getMaxNumberPassengers() : int
+ setMaxNumberPassengers(in maxNumberPassengers : int) : void
+ toString() : String
}

Ship <|-- CargoShip
Ship <|-- CruiseShip


@enduml