@startuml
'https://plantuml.com/object-diagram

object "<u>c1:Course</u>" as crs{
    name = "CS5800 - Advanced Software Engineering"
}
object "<u>c1Instructor: Instructor </u>" as crsInst{
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
 }
object "<u>c1Textbook:Textbook</u>" as crsText{
    author = "Robert Cecil Martin"
    publisher = "Pearson"
    title = "CleanCode:A Handbook of Agile Software Craftsmanship"
}


crs o-- crsInst
crs o-- crsText
@enduml
